server:
  servlet:
    context-path: /api
  port: 8080


logging:
  level:
    root: info
    com.yuki.springbootdemo: debug
  file: logs/debug.log

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Book?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: zyy85858776


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


